name: Call a reusable workflow

on:
  watch:
    types: [started]

jobs:
  call-workflow:
    uses: WordsWorthLess/openwrt/.github/workflows/build.yml@master
    with:
      target: 'X86/64'
      testing: false
      build_toolchain: true
      include_feeds: true
      build_full: true
      build_kernel: true
      build_all_modules: true
      build_all_kmods: true
      build_all_boards: true
      use_openwrt_container: true
